export const busRoutes = [
  { "bus": "1", "stops": ["28 May", "Sahil", "Azneft", "Bayraq Meydanı", "20-ci Sahə"] },
  { "bus": "2", "stops": ["Avtovağzal", "Biləcəri", "20 Yanvar", "28 May", "Dərnəgül"] },
  { "bus": "3", "stops": ["Dərnəgül", "Nərimanov", "Gənclik", "Sahil", "Badamdar"] },
  { "bus": "5", "stops": ["Nərimanov", "Gənclik", "28 May", "Sahil", "20-ci Sahə"] },
  { "bus": "6", "stops": ["Əhmədli", "Xalqlar Dostluğu", "Neftçilər", "Qara Qarayev", "Koroğlu"] },
  { "bus": "7A", "stops": ["Azadlıq prospekti", "Gənclik", "28 May", "Sahil", "İçərişəhər"] },
  { "bus": "8", "stops": ["Həzi Aslanov", "Əhmədli", "Xalqlar Dostluğu", "Neftçilər", "Koroğlu"] },
  { "bus": "9", "stops": ["Nərimanov", "Gənclik", "28 May", "Sahil", "Bayıl"] },
  { "bus": "10", "stops": ["Nərimanov", "Gənclik", "Elmlər Akademiyası", "Yasamal", "Yeni Yasamal"] },
  { "bus": "11", "stops": ["28 May", "Nərimanov", "Koroğlu", "Neftçilər", "Həzi Aslanov"] },
  { "bus": "13", "stops": ["Dərnəgül", "Azadlıq prospekti", "Gənclik", "28 May", "Sahil"] },
  { "bus": "14", "stops": ["Xətai", "28 May", "Nizami", "Elmlər Akademiyası", "İnşaatçılar"] },
  { "bus": "15", "stops": ["Neftçilər", "Qara Qarayev", "Koroğlu", "Nərimanov", "Gənclik"] },
  { "bus": "16", "stops": ["Həzi Aslanov", "Əhmədli", "Xalqlar Dostluğu", "Neftçilər", "Koroğlu"] },
  { "bus": "17", "stops": ["Yeni Yasamal", "Elmlər Akademiyası", "Nizami", "28 May", "Nərimanov"] },
  { "bus": "18", "stops": ["Sahil", "İçərişəhər", "Bayıl", "Badamdar", "20-ci Sahə"] },
  { "bus": "19", "stops": ["Nərimanov", "Gənclik", "28 May", "Nizami", "Elmlər Akademiyası"] },
  { "bus": "20", "stops": ["Nizami", "28 May", "Gənclik", "Nərimanov", "Koroğlu"] },
  { "bus": "21", "stops": ["Dərnəgül", "Nərimanov", "Gənclik", "28 May", "Sahil"] },
  { "bus": "22", "stops": ["Xətai", "28 May", "Nizami", "Elmlər Akademiyası", "20 Yanvar"] },
  { "bus": "24", "stops": ["Əhmədli", "Xalqlar Dostluğu", "Neftçilər", "Qara Qarayev", "Koroğlu"] },
  { "bus": "26", "stops": ["Nərimanov", "Gənclik", "28 May", "Sahil", "Bayıl"] },
  { "bus": "28", "stops": ["Dərnəgül", "Azadlıq prospekti", "Gənclik", "28 May", "Sahil"] },
  { "bus": "30", "stops": ["Avtovağzal", "20 Yanvar", "Nizami", "28 May", "Nərimanov"] },
  { "bus": "32", "stops": ["Həzi Aslanov", "Əhmədli", "Xalqlar Dostluğu", "Neftçilər", "Koroğlu"] },
  { "bus": "35", "stops": ["Nərimanov", "Gənclik", "28 May", "Sahil", "İçərişəhər"] },
  { "bus": "36", "stops": ["Elmlər Akademiyası", "İnşaatçılar", "20 Yanvar", "Memar Əcəmi", "Nəsimi"] },
  { "bus": "37", "stops": ["Nərimanov", "Koroğlu", "Qara Qarayev", "Neftçilər", "Xalqlar Dostluğu"] },
  { "bus": "38", "stops": ["Xətai", "28 May", "Gənclik", "Nərimanov", "Koroğlu"] },
  { "bus": "41", "stops": ["Yeni Yasamal", "Elmlər Akademiyası", "Nizami", "28 May", "Gənclik"] },
  { "bus": "44", "stops": ["Neftçilər", "Qara Qarayev", "Koroğlu", "Nərimanov", "Gənclik"] },
  { "bus": "49", "stops": ["Dərnəgül", "Azadlıq prospekti", "Gənclik", "28 May", "Sahil"] },
  { "bus": "50", "stops": ["Nərimanov", "Gənclik", "28 May", "Sahil", "Bayıl"] },
  { "bus": "52", "stops": ["Əhmədli", "Xalqlar Dostluğu", "Neftçilər", "Qara Qarayev", "Koroğlu"] },
  { "bus": "53", "stops": ["Xətai", "28 May", "Nizami", "Elmlər Akademiyası", "İnşaatçılar"] },
  { "bus": "60", "stops": ["Memar Əcəmi", "Nəsimi", "Azadlıq prospekti", "Dərnəgül", "Nərimanov"] },
  { "bus": "61", "stops": ["Nərimanov", "Gənclik", "28 May", "Sahil", "İçərişəhər"] },
  { "bus": "65", "stops": ["Dərnəgül", "Azadlıq prospekti", "Gənclik", "28 May", "Sahil"] },
  { "bus": "67", "stops": ["Həzi Aslanov", "Əhmədli", "Xalqlar Dostluğu", "Neftçilər", "Qara Qarayev"] },
  { "bus": "70", "stops": ["Nizami", "28 May", "Gənclik", "Nərimanov", "Koroğlu"] },
  { "bus": "79", "stops": ["Dərnəgül", "Nərimanov", "Gənclik", "28 May", "Sahil"] },
  { "bus": "81", "stops": ["Elmlər Akademiyası", "İnşaatçılar", "20 Yanvar", "Memar Əcəmi", "Nəsimi"] },
  { "bus": "85", "stops": ["Nərimanov", "Gənclik", "28 May", "Sahil", "Bayıl"] },
  { "bus": "88", "stops": ["Dərnəgül", "Azadlıq prospekti", "28 May", "Sahil", "20-ci Sahə"] },
  { "bus": "90", "stops": ["Həzi Aslanov", "Əhmədli", "Xalqlar Dostluğu", "Neftçilər", "Qara Qarayev"] },
  { "bus": "96", "stops": ["Nərimanov", "Koroğlu", "Qara Qarayev", "Neftçilər", "Xalqlar Dostluğu"] },
  { "bus": "125", "stops": ["Binəqədi", "Dərnəgül", "Azadlıq prospekti", "Gənclik", "28 May"] },
  { "bus": "135", "stops": ["Avtovağzal", "20 Yanvar", "Memar Əcəmi", "Nəsimi", "Azadlıq prospekti"] }
];

export const metroRoutes = [
  { "name": "Qırmızı Xətt", "stops": ["İçərişəhər", "Sahil", "28 May", "Gənclik", "Nəriman Nərimanov", "Bakmil", "Ulduz", "Koroğlu", "Qara Qarayev", "Neftçilər", "Xalqlar Dostluğu", "Əhmədli", "Həzi Aslanov"] },
  { "name": "Yaşıl Xətt", "stops": ["Xətai", "28 May", "Nizami", "Elmlər Akademiyası", "İnşaatçılar", "20 Yanvar", "Memar Əcəmi", "Nəsimi", "Azadlıq prospekti", "Dərnəgül"] },
  { "name": "Bənövşəyi Xətt", "stops": ["Xocəsən", "Avtovağzal", "Memar Əcəmi", "8 Noyabr"] }
];
